### ISSUE TITLE
FormatQuickBar is not stable

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#1066]
In chrome
1. Select from front to back
2. Move the mouse horizontally to move out of the frame

https://user-images.githubusercontent.com/27926/217407912-1c4499bf-5de2-4db9-b132-f69fd9f86225.mov

```
utils.ts:16 Uncaught Error: val does not exist
    at assertExists (utils.ts:16:11)
    at getFormat (container-operations.ts:197:5)
    at FormatQuickBar.connectedCallback (format-bar-node.ts:82:19)
    at showFormatQuickBar (index.ts:129:13)
    at DefaultSelectionManager._showFormatQuickBar (selection-manager.ts:500:7)
    at DefaultSelectionManager._onContainerDragEnd (selection-manager.ts:489:10)
    at HTMLDocument.mouseUpHandler (gesture.ts:170:7)
```

**Comment by lawvs** [comment]
I believe this issue has been fixed. If you can still reproduce it, please feel free to reopen it.

**Comment by fundon** [comment]
I tested it. LGTM
