### ISSUE TITLE
Can not run dev environment

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#171]
Potentially an issue isolated to Apple M-series chips.

Error on M1 (Pro).

<img width="980" alt="Screen Shot 2022-11-04 at 09 42 11" src="https://user-images.githubusercontent.com/4605025/199867807-3aea9d41-edd0-449b-be8c-e8e8a299fcfb.png">

**Comment by doodlewind** [comment]
I'm not sure why there is the Tailwind related stuff, since we don't have BlockSuite depending on it.

Could you clone the repository in a standalone directory, then perform a fresh install using `pnpm install` and `pnpm dev`? You can post the command line output of your installation, and we can figure out if the environment work right.

**Comment by ShortCipher5** [comment]
Still receiving this error on a fresh deployment (Windows device has no issue).

Found something that potentially is similar in nature: https://github.com/facebook/docusaurus/issues/6631.

**Comment by doodlewind** [comment]
Could you post the command line output of your installation?

**Comment by ShortCipher5** [comment]
10:31:06 AM [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')
  Plugin: vite:css
  File: /Users/toeverything/Documents/GitHub/blocksuite2/packages/playground/src/style.css
      at getTailwindConfig (/Users/toeverything/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:84:63)
      at /Users/toeverything/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:96:92
      at /Users/toeverything/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
      at plugins (/Users/toeverything/node_modules/tailwindcss/lib/index.js:38:63)
      at LazyResult.runOnRoot (/Users/toeverything/Documents/GitHub/blocksuite2/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/Users/toeverything/Documents/GitHub/blocksuite2/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/lazy-result.js:393:26)
      at LazyResult.async (/Users/toeverything/Documents/GitHub/blocksuite2/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/lazy-result.js:221:30)
      at LazyResult.then (/Users/toeverything/Documents/GitHub/blocksuite2/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/lazy-result.js:206:17)

**Comment by lawvs** [comment]
I think this issue is related to the vite and there is a similar issue https://github.com/vitejs/vite/issues/9506, I will look into more details.

**Comment by ShortCipher5** [comment]
Trying to read config from another project - removing that config allows to run error-free.
