### ISSUE TITLE
database: TypeError: Class extends value undefined is not a constructor or null at eval

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#2018]
The database module in blocksuite cannot be loaded in AFFiNE.

blocksuite and AFFiNE are the latest codes.

/cc @zqran 

```
Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null at eval (webpack-internal:///../../../blocksuite/packages/blocks/src/database-block/components/toolbar/toolbar.ts:69:121) at ../../../blocksuite/packages/blocks/src/database-block/components/toolbar/toolbar.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:898:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/blocks/src/database-block/database-block.ts:9:88) at ../../../blocksuite/packages/blocks/src/database-block/database-block.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:920:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/blocks/src/database-block/index.ts:2:76) at ../../../blocksuite/packages/blocks/src/database-block/index.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:931:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/blocks/src/index.ts:20:83) at ../../../blocksuite/packages/blocks/src/index.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:1096:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/editor/src/components/editor-container.ts:7:76) at ../../../blocksuite/packages/editor/src/components/editor-container.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:1943:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/editor/src/components/index.ts:2:78) at ../../../blocksuite/packages/editor/src/components/index.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:1954:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../../blocksuite/packages/editor/src/index.ts:2:78) at ../../../blocksuite/packages/editor/src/index.ts (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:1976:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///../../packages/component/src/components/block-suite-editor/index.tsx:6:76) at ../../packages/component/src/components/block-suite-editor/index.tsx (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:29:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at eval (webpack-internal:///./src/components/blocksuite/block-suite-editor/index.tsx:5:94) at ./src/components/blocksuite/block-suite-editor/index.tsx (http://localhost:8080/_next/static/chunks/src_components_blocksuite_block-suite-editor_index_tsx.js:18:1) at options.factory (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:733:31) at __webpack_require__ (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:37:33) at Function.fn (http://localhost:8080/_next/static/chunks/webpack.js?ts=1681197512235:388:21) at async next_dynamic__WEBPACK_IMPORTED_MODULE_2___default.loadableGenerated.modules (webpack-internal:///./src/components/page-detail-editor.tsx:31:79)
```
<img width="1284" alt="Screenshot 2023-04-11 at 3 22 24 PM" src="https://user-images.githubusercontent.com/27926/231092503-a154a9b4-8514-4e4e-8484-01c6746dc944.png">

**Comment by doodlewind** [comment]
@zqran this may relate to some recent refactoring that splits database block modules, since the side effect import (`import './my-component.js'`) is required for loading lit components, otherwise it may got tree-shaked and would not be registered.

This is because we usually use the `<my-component>` tag but not importing `MyComponent` in Lit, so the `MyComponent` module file may be tree-shaked.
