### ISSUE TITLE
Console error on collaboration test cases

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#286]
Following error are randomly thrown in playwright console:

```
Unexpected console error: TypeError: Cannot read properties of undefined (reading 'id')
    at Store.removeSpace (http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/store.ts?t=1670451298738:26:30)
    at http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/workspace/workspace.ts?t=1670866875269:158:19
    at http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/utils/signal.ts:86:9
    at Array.forEach (<anonymous>)
    at Signal.emit (http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/utils/signal.ts:84:20)
    at http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/workspace/workspace.ts?t=1670866875269:26:28
    at Set.forEach (<anonymous>)
    at WorkspaceMeta._handlePageEvent (http://localhost:5173/@fs/Users/ewind/code/blocksuite/packages/store/src/workspace/workspace.ts?t=1670866875269:23:18)
    at callAll (http://localhost:5173/node_modules/.vite/deps/chunk-LZSYNGME.js?v=6985b3fb:748:12)
    at callEventHandlerListeners (http://localhost:5173/node_modules/.vite/deps/chunk-LZSYNGME.js?v=6985b3fb:1898:63)
```

This fails e0e6e1291b7c0b439b91c73f677872d99fbc1485 and this check has to be disabled temporally.

To reproduce, mark the test case `'basic multi user state'` (or any test case that requires `pageA` and `pageB`) as `test.only`, then run `pnpm test -- basic.spec.ts --repeat-each=10`. But this still happens occasionally.

Part of #216

**Comment by doodlewind** [comment]
Closed by #2209
