### ISSUE TITLE
Console error exporting PNG/PDF in playground

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3115]
Console error: 

```
index.ts:145 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5173/node_modules/.vite/deps/html2canvas.js?v=db7c62c1
```

**Comment by doodlewind** [comment]
Console error after restarting pnpm:

```
block-hub.ts:556 Uncaught TypeError: Cannot read properties of undefined (reading 'page')
    at new BlockHub (block-hub.ts:556:26)
    at DocumentCloner2.createElementClone (document-cloner.ts:156:28)
    at DocumentCloner2.cloneNode (document-cloner.ts:318:32)
    at DocumentCloner2.appendChildNode (document-cloner.ts:284:40)
    at DocumentCloner2.cloneChildNodes (document-cloner.ts:301:22)
    at DocumentCloner2.cloneNode (document-cloner.ts:340:22)
    at DocumentCloner2.appendChildNode (document-cloner.ts:284:40)
    at DocumentCloner2.cloneChildNodes (document-cloner.ts:301:22)
    at DocumentCloner2.cloneNode (document-cloner.ts:340:22)
    at new DocumentCloner2 (document-cloner.ts:69:37)
BlockHub @ block-hub.ts:556
DocumentCloner2.createElementClone @ document-cloner.ts:156
DocumentCloner2.cloneNode @ document-cloner.ts:318
DocumentCloner2.appendChildNode @ document-cloner.ts:284
DocumentCloner2.cloneChildNodes @ document-cloner.ts:301
DocumentCloner2.cloneNode @ document-cloner.ts:340
DocumentCloner2.appendChildNode @ document-cloner.ts:284
DocumentCloner2.cloneChildNodes @ document-cloner.ts:301
DocumentCloner2.cloneNode @ document-cloner.ts:340
DocumentCloner2 @ document-cloner.ts:69
(anonymous) @ index.ts:90
step @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderElement @ index.ts:29
html2canvas @ index.ts:20
transPageToCanvas @ index.ts:94
await in transPageToCanvas (async)
exportPng @ index.ts:136
_exportPng @ debug-menu.ts:288
handleEvent @ lit-html.ts:2010
Show 17 more frames
```

**Comment by qiuqfang** [comment]
This seems to be caused by clone via html2canvas
https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/__internal__/content-parser/index.ts#L94

**Comment by zuoxiaodong0815** [comment]
The BlockHub node isn't important for exporting, so we can skip this element node.
