### ISSUE TITLE
Occur 'Failed to get current range' error after dragging blocks outside frame and clicking at blank area when edgeless mode

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3125]
Steps to reproduce:
1. Edgeless mode.
2. Drag blocks outside a frame.
3. Click at blank area (outside the frames)

https://github.com/toeverything/blocksuite/assets/99816898/4430c1be-d9e7-45bc-8934-52a159a8afad

**Comment by donteatfriedrice** [comment]
Error message:

selection.ts:339 Uncaught Error: Failed to get current range, rangeCount is 0
    at getCurrentNativeRange (selection.ts:339:11)
    at getNativeSelectionMouseDragInfo (position.ts:89:20)
    at DefaultModeController.onContainerDragEnd (default-mode.ts:498:43)
    at EdgelessSelectionManager._onContainerDragEnd (selection-manager.ts:321:35)
    at selection-manager.ts:214:12
    at UIEventDispatcher.run (dispatcher.ts:81:22)
    at run (pointer.ts:98:26)
    at PointerControl._up (pointer.ts:110:5)

**Comment by doodlewind** [comment]
Not reproduced since we don't support dragging block outside of note FTM. It's suggested to use block slicer instead.
