### ISSUE TITLE
toast unstable

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#3339]
When running toast multiple times, an exception will be reported

```
toast.ts:80 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'animate')
    at toast (toast.ts:80:11)
toast @ toast.ts:80
await in toast (async)
(anonymous) @ edgeless-page-block.ts:606
Promise.finally (async)
(anonymous) @ edgeless-page-block.ts:604
(anonymous) @ slot.ts:106
emit @ slot.ts:104
EdgelessMoreButton._runAction @ more-button.ts:170
(anonymous) @ more-button.ts:46
handleEvent @ lit-html.ts:2010
Show 1 more frame
toast.ts:80 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'animate')
    at toast (toast.ts:80:11)
```

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/pull/3183
