### ISSUE TITLE
Cannot read properties of undefined (reading 'insert')

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3444]
```shell
TypeError: Cannot read properties of undefined (reading 'insert')
    at eval (yjs.cjs:7040:1)
    at transact (yjs.cjs:3377:1)
    at YText.applyDelta (yjs.cjs:7036:1)
    at eval (yjs.cjs:7058:35)
    at eval (yjs.cjs:6958:35)
    at Array.forEach (<anonymous>)
    at YText._integrate (yjs.cjs:6958:35)
    at ContentType.integrate (yjs.cjs:9284:1)
    at Item.integrate (yjs.cjs:9846:1)
    at typeMapSet (yjs.cjs:5520:1)
    at eval (yjs.cjs:6050:1)
    at transact (yjs.cjs:3377:1)
    at YMap.set (yjs.cjs:6049:1)
    at eval (yjs.cjs:5911:1)
    at Map.forEach (<anonymous>)
    at YMap._integrate (yjs.cjs:5910:35)
    at ContentType.integrate (yjs.cjs:9284:1)
    at Item.integrate (yjs.cjs:9846:1)
    at typeMapSet (yjs.cjs:5520:1)
    at eval (yjs.cjs:6050:1)
    at transact (yjs.cjs:3377:1)
    at YMap.set (yjs.cjs:6049:1)
    at eval (yjs.cjs:5911:1)
    at Map.forEach (<anonymous>)
    at YMap._integrate (yjs.cjs:5910:35)
    at ContentType.integrate (yjs.cjs:9284:1)
    at Item.integrate (yjs.cjs:9846:1)
    at typeMapSet (yjs.cjs:5520:1)
    at eval (yjs.cjs:6050:1)
    at transact (yjs.cjs:3377:1)
    at YMap.set (yjs.cjs:6049:1)
    at eval (utils.js:49:1)
    at Array.forEach (<anonymous>)
    at syncBlockProps (utils.js:28:1)
    at eval (page.js:258:27)
    at transact (yjs.cjs:3377:1)
    at Doc.transact (yjs.cjs:561:1)
    at Page.transact (space.js:75:1)
    at Page.transact (page.js:119:1)
    at Page.addBlock (page.js:250:1)
    at Page.debugWrapper (debug.js:38:1)
    at addBlockByProps (workspace.js:281:1)
    at async eval (workspace.js:284:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
    at async eval (workspace.js:283:1)
```

**Comment by doodlewind** [comment]
How to reproduce this?

**Comment by fourdim** [comment]
To reproduce this:
1. Close the Affine Application.
2. Open the Affine Application.
3. Create a new workspace.
4. Create a new workspace.

Whenever you see this error. You will see a log beside it. It can be either above this error, or below this error.
![image](https://github.com/toeverything/blocksuite/assets/59462000/c56ef427-b71b-4e9c-812a-fe59b143c321)

The log will be something like:
```
push /workspace/*******/*******-hello-world false 2 1
```

**Comment by doodlewind** [comment]
@fourdim huge thank for your reproduction! Investing on this has higher priority than regular refactoring. So would be great if you can keep trying, or just ping anyone if needed.

**Comment by fourdim** [comment]
https://github.com/toeverything/AFFiNE/issues/3886

A fix will be implemented soon.
