### ISSUE TITLE
yText must be attached to a Y.Doc

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3967]
In OKR template in the latest canary

```shell
yText must be attached to a Y.Doc
  at new VEditor (webpack-internal:///./node_modules/@blocksuite/virgo/dist/virgo.js:82:19)
  at RichTextCell._onInitVEditor (webpack-internal:///./node_modules/@blocksuite/blocks/dist/database-block/common/columns/rich-text/cell-renderer.js:95:24)
  at RichTextCell.firstUpdated (webpack-internal:///./node_modules/@blocksuite/blocks/dist/database-block/common/columns/rich-text/cell-renderer.js:78:14)
  at RichTextCell._$didUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:874:18)
  at RichTextCell.performUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:842:18)
  at RichTextCell.scheduleUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:761:21)
  at RichTextCell.__enqueueUpdate (webpack-internal:///./node_modules/@lit/reactive-element/development/reactive-element.js:734:29)
```

**Comment by himself65** [comment]
JSON snapshot:

https://github.com/toeverything/AFFiNE/blob/master/packages/templates/v1/okr-template.json
