### ISSUE TITLE
edgeless failed to load

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#4692]
![image](https://github.com/toeverything/blocksuite/assets/59462000/db24b27c-cbf2-4e30-af7d-7e65996c8de2)

```
block-element.ts:56 Uncaught TypeError: Cannot read properties of undefined (reading 'propsUpdated')
    at U0.connectedCallback (block-element.ts:56:3)
    at U0.connectedCallback (surface-block.ts:217:12)
    at R.k (lit-html.js:6:4627)
    at R.$ (lit-html.js:6:4701)
    at R.g (lit-html.js:6:5085)
    at R._$AI (lit-html.js:6:4534)
    at D (lit-html.js:6:7898)
    at Gr.update (lit-element.js:6:406)
    at Gr.update (edgeless-page-block.ts:118:28)
    at Gr.performUpdate (reactive-element.js:6:4846)
edgeless-page-block.ts:282 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slots')
    at Gr._initSlotEffects (edgeless-page-block.ts:282:21)
    at Gr.firstUpdated (edgeless-page-block.ts:113:14)
    at Gr._$AE (reactive-element.js:6:5109)
    at Gr.performUpdate (reactive-element.js:6:4911)
    at Gr.scheduleUpdate (reactive-element.js:6:4493)
    at Gr._$Ej (reactive-element.js:6:4401)
surface-block.ts:587 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attach')
    at U0.attach (surface-block.ts:587:1)
    at U0.firstUpdated (surface-block.ts:371:11)
    at U0._$AE (reactive-element.js:6:5109)
    at U0.performUpdate (reactive-element.js:6:4911)
    at U0.scheduleUpdate (reactive-element.js:6:4493)
    at U0._$Ej (reactive-element.js:6:4401)
edgeless-blocks-container.ts:200 Uncaught (in promise) TypeError: Cannot destructure property 'left' of '((Bn(...).s[79]++) , t)' as it is undefined.
    at x6.render (edgeless-blocks-container.ts:200:10)
    at x6.update (lit-element.js:6:304)
    at x6.performUpdate (reactive-element.js:6:4846)
    at x6.scheduleUpdate (reactive-element.js:6:4493)
    at x6._$Ej (reactive-element.js:6:4401)
```

**Comment by fourdim** [comment]
To reproduce:
Go to https://blocksuite-toeverything.vercel.app/?init=preset
