### ISSUE TITLE
build issue using esbuild

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#4827]
```
Uncaught Error: Dynamic require of "buffer" is not supported
    at chunk-WXJVIN7F.js?v=9a2581a8:14:9
    at node_modules/.vite-electron-renderer/buffer.mjs (buffer.mjs:1:50)
    at __init (chunk-WXJVIN7F.js?v=9a2581a8:17:56)
    at service.ts:3:1
```

**Comment by doodlewind** [comment]
Tracked in https://github.com/toeverything/blocksuite-ecosystem-ci/issues/3

**Comment by sxzz** [comment]
See [esbuild example](https://github.com/toeverything/blocksuite-ecosystem-ci/tree/main/packages/esbuild)
