### ISSUE TITLE
 Cannot read properties of undefined (reading 'dispose') and unable to use Edgeless editor

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6643]
Im getting above error while I try to switch the editor .

Here is my code

Here is my component 
`
export const EditorContainer = (props: Props) => {
   const { setEditor } = props

   const { editor, toggleEditorMode } = useEditor()!

   const editorContainerRef = useRef<HTMLDivElement>(null)

   useEffect(() => {
      if (editorContainerRef.current && editor) {
         editorContainerRef.current.innerHTML = ''
         editorContainerRef.current.appendChild(editor)

         setEditor(editor)
      }
   }, [editor])

   const onButtonClick = () => {
      toggleEditorMode()
   }

   return (
      <div className='flex w-full h-full'>
         <button onClick={onButtonClick}>Toggle ;)</button>
         <div className='editor-container w-full' ref={editorContainerRef} />
      </div>
   )
}

`

Related context

`import React, { useEffect, createContext, useContext, useState } from 'react'
import { literal } from 'lit/static-html.js'

import { EdgelessEditor, PageEditor } from '@blocksuite/presets'
import '@blocksuite/presets/themes/affine.css'
import { DocSnapshot, Workspace, Job, Schema } from '@blocksuite/store'
import {
   AffineSchemas,
   EdgelessEditorBlockSpecs,
   PageEditorBlockSpecs
} from '@blocksuite/blocks'

import {
   S3ImageBlockSchema,
   S3ImageService
} from '../../../schema/S3Image/schema'
import { S3ImageBlockComponent } from '../../../schema/S3Image'

export const EditorContext = createContext<{
   editor: EdgelessEditor | PageEditor
   workspace: Workspace
   loadPage: () => void
   toggleEditorMode: () => void
} | null>(null)

export function useEditor() {
   return useContext(EditorContext)
}

export const EditorProvider = ({
   children,
   initialContent
}: {
   children: React.ReactNode
   initialContent?: DocSnapshot
}) => {
   const { editor, workspace, loadPage, toggleEditorMode } = useEditorData()

   useEffect(() => {
      loadPage(initialContent)
   }, [])

   if (!editor) {
      return <></>
   }

   return (
      <EditorContext.Provider
         value={{
            editor: editor as EdgelessEditor | PageEditor,
            workspace,
            loadPage,
            toggleEditorMode
         }}
      >
         {children}
      </EditorContext.Provider>
   )
}

const editorDefaultContent: DocSnapshot = {
   type: 'page',
   meta: { id: '123456', title: '', createDate: 1710502643842, tags: [] },
   blocks: {
      type: 'block',
      id: 'RMDZEWB2T8',
      flavour: 'affine:page',
      version: 2,
      props: { title: { '$blocksuite:internal:text$': true, delta: [] } },
      children: [
         {
            type: 'block',
            id: 'E2yVZsZILc',
            flavour: 'affine:surface',
            version: 5,
            props: {
               elements: {}
            },
            children: []
         }
      ]
   }
}

export const useEditorData = () => {
   const filteredAffineSchemas = AffineSchemas.filter(
      schema => schema.model.flavour !== 'affine:image'
   )

   const schema = new Schema().register([
      ...filteredAffineSchemas,
      S3ImageBlockSchema
   ])
   const workspace = new Workspace({ schema })
   const [edgelessEditor, setEdgelessEditor] = useState<EdgelessEditor | null>()

   const [pageEditor, setPageEditor] = useState<PageEditor | null>()

   const [editorMode, setEditorMode] = useState('edgeless')

   const job = new Job({ workspace })

   const loadPage = async (initialContent?: DocSnapshot) => {
      const editorData = initialContent ? initialContent : editorDefaultContent

      const docWithContent = await job.snapshotToDoc(editorData)

      const newEdgelessEditor = new EdgelessEditor()
      const newPageEditor = new PageEditor()
      newEdgelessEditor.doc = docWithContent
      newPageEditor.doc = docWithContent
      setEdgelessEditor(newEdgelessEditor)
      setPageEditor(newPageEditor)

      const filteredEdgelessEditorBlockSpecs = EdgelessEditorBlockSpecs.filter(
         blockSpec => blockSpec.schema.model.flavour !== 'affine:image'
      )

      const filteredPageEditorBlockSpecs = PageEditorBlockSpecs.filter(
         blockSpec => blockSpec.schema.model.flavour !== 'affine:image'
      )

      newEdgelessEditor.specs = [
         ...filteredEdgelessEditorBlockSpecs,
         {
            schema: S3ImageBlockSchema,
            service: S3ImageService,
            view: {
               component: literal`affine-s3-image`,
               widgets: {
                  imageToolbar: literal`affine-image-toolbar-widget`
               }
            }
         }
      ]

      newPageEditor.specs = [
         ...filteredPageEditorBlockSpecs,
         {
            schema: S3ImageBlockSchema,
            service: S3ImageService,
            view: {
               component: literal`affine-s3-image`,
               widgets: {
                  imageToolbar: literal`affine-image-toolbar-widget`
               }
            }
         }
      ]

      //@ts-ignore
      const s3Image = S3ImageBlockComponent //TODO: need to remove this
   }

   const toggleEditorMode = () => {
      if (editorMode === 'edgeless') {
         setEditorMode('page')
      } else {
         setEditorMode('edgeless')
      }
   }

   const getEditor = () => {
      if (editorMode === 'page') {
         return pageEditor
      }
      return edgelessEditor
   }

   return {
      editor: getEditor(),
      workspace,
      loadPage,
      setPageEditor,
      toggleEditorMode
   }
}
`

I'm toggling the editor on button click. page editor is working fine but i'm getting the above error in edgeless editor and im unable to perform any action in edgeless editor.

Can anyone help me with this @lawvs

**Comment by Flrande** [comment]
What is the error, I did not see a screenshot or error output

**Comment by RajaTheKing826** [comment]
```
vendor.js:172452 TypeError: Cannot read properties of undefined (reading 'dispose')
    at disposeAll (vendor.js:172449:24)
    at DisposableGroup.dispose (vendor.js:172436:9)
    at EdgelessRootBlockComponent.disconnectedCallback (vendor.js:175011:31)
    at EdgelessRootBlockComponent.disconnectedCallback (vendor.js:175212:15)
    at EdgelessRootBlockComponent.disconnectedCallback (vendor.js:108160:15)
    at main.js:123779:44
    at commitHookEffectListMount (vendor.js:508179:26)
    at commitPassiveMountOnFiber (vendor.js:509955:13)
    at commitPassiveMountEffects_complete (vendor.js:509920:9)
    at commitPassiveMountEffects_begin (vendor.js:509907:7) '\n    at EditorContainer (http://localhost:3000/main.js:123770:5)\n    at EditorProvider (http://localhost:3000/main.js:123635:3)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at LoadingWrapper (http://localhost:3000/main.js:149040:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at LoadingWrapper (http://localhost:3000/main.js:149040:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at div\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at PageHeaderConfigProvider (http://localhost:3000/main.js:123819:57)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at PageContextProvider (http://localhost:3000/main.js:121077:71)\n    at PageSidepaneUIStoreProvider (http://localhost:3000/main.js:124728:5)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at Route (http://localhost:3000/vendor.js:547610:29)\n    at Switch (http://localhost:3000/vendor.js:547812:29)\n    at Suspense\n    at SuspenseWithLoader (http://localhost:3000/main.js:150122:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at GlobalHotKeys (http://localhost:3000/vendor.js:523644:5)\n    at div\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at LoadingWrapper (http://localhost:3000/main.js:149040:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at http://localhost:3000/vendor.js:452650:35\n    at Route (http://localhost:3000/vendor.js:547610:29)\n    at Switch (http://localhost:3000/vendor.js:547812:29)\n    at Suspense\n    at SuspenseWithLoader (http://localhost:3000/main.js:150122:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at div\n    at O (http://localhost:3000/vendor.js:580998:36103)\n    at div\n    at O (http://localhost:3000/vendor.js:580998:36103)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at LoadingWrapper (http://localhost:3000/main.js:149040:1)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at Route (http://localhost:3000/vendor.js:547610:29)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at Switch (http://localhost:3000/vendor.js:547812:29)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at TrashStoreProvider (http://localhost:3000/main.js:44438:38)\n    at SharedUsersStoreProvider (http://localhost:3000/main.js:48996:44)\n    at FilesStoreProvider (http://localhost:3000/main.js:42500:38)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at FolderManagementStoreProvider (http://localhost:3000/main.js:62487:49)\n    at HiveCoreStoresProvider (http://localhost:3000/main.js:63044:3)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at NavbarStoreProvider (http://localhost:3000/main.js:82251:39)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at UsersStoreStoreProvider (http://localhost:3000/main.js:70598:38)\n    at IAMStoresProvider (http://localhost:3000/main.js:70963:19)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at APISauceCreateWithAuthProvider (http://localhost:3000/main.js:144422:5)\n    at ApolloProvider (http://localhost:3000/vendor.js:7006:21)\n    at ApolloClientWithAuthProvider (http://localhost:3000/main.js:144323:5)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at UserStoreProvider (http://localhost:3000/main.js:64482:5)\n    at MoveItemsUIStoreProvider (http://localhost:3000/main.js:52364:19)\n    at CardsUIStoreProvider (http://localhost:3000/main.js:124674:5)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at AuthSessionProvider (http://localhost:3000/main.js:144280:5)\n    at CookieAuthSessionProvider (http://localhost:3000/main.js:144659:5)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at I18nextProvider (http://localhost:3000/vendor.js:524905:5)\n    at Provider (http://localhost:3000/vendor.js:452619:24)\n    at Suspense\n    at SuspenseWithLoader (http://localhost:3000/main.js:150122:1)\n    at QueryClientProvider (http://localhost:3000/vendor.js:641437:3)\n    at observerComponent (http://localhost:3000/vendor.js:451961:16)\n    at Router (http://localhost:3000/vendor.js:547229:30)\n    at BrowserRouter (http://localhost:3000/vendor.js:546662:35)'
```

this is the error

**Comment by doodlewind** [comment]
@RajaTheKing826 could you reproduce this in the [react-basic](https://github.com/toeverything/blocksuite/tree/master/examples/react-basic) example? Would help a lot to make sure whether this depends on bundler environment.

**Comment by RajaTheKing826** [comment]
do i have to clone that react-basic example and need to reproduce that ? or any other ways?

**Comment by golok727** [comment]
> do i have to clone that react-basic example and need to reproduce that ? or any other ways?

You're correct. Clone the example, replicate the process, and verify if the error persists.

**Comment by RajaTheKing826** [comment]
I have used AffineEditorContainer for editor switch which resolved my issue.
